// list comes from whole food's website

//https://www.wholefoodsmarket.com/quality-standards/food-ingredient-standards?utm_source=paidgoogle&utm_medium=paidsearch&utm_campaign=&utm_content=paid_global&gad_source=1&gad_campaignid=22042553025&gbraid=0AAAAAC11_r1fssA2pT24A1GMEWgjvDb4B&gclid=Cj0KCQjw37nNBhDkARIsAEBGI8Oc_97mujI4K4QBN04rrEtZz1jq-3S9LXz6VYkCRjV7qVzFPf83W5oaAkILEALw_wcB

export const wholeFoodsBannedList = [
  "2,4,5-trihydroxybutyrophenone (THBP)",
  "5-HTP",
  "acesulfame-K",
  "acetoin (synthetic)",
  "acetylated esters of mono- and diglycerides",
  "activated charcoal",
  "advantame",
  "alkanna tinctoria",
  "allulose",
  "aluminum ammonium sulfate",
  "aluminum potassium sulfate",
  "aluminum starch octenylsuccinate",
  "aluminum sulfate",
  "ammonium alum",
  "ammonium chloride",
  "ammonium saccharin",
  "ammonium sulfate",
  "apricot kernel/extract",
  "aspartame",
  "azo dyes",
  "azodicarbonamide",
  "Bacillus coagulans ProDURA UABc-20",
  "bacopa",
  "bentonite",
  "benzoates",
  "benzoic acid",
  "benzophenone",
  "benzoyl peroxide",
  "benzyl alcohol",
  "Benzyl benzoate",
  "beta-cyclodextrin",
  "BHA (butylated hydroxyanisole)",
  "BHT (butylated hydroxytoluene)",
  "black soldier fly",
  "bleached flour",
  "blessed thistle",
  "bromated flour",
  "brominated vegetable oil",
  "bryonia root",
  "burnt alum",
  "butylparaben",
  "caffeine (extended release)",
  "calcium benzoate",
  "calcium disodium EDTA",
  "calcium propionate",
  "calcium saccharin",
  "calcium sorbate",
  "calcium stearoyl-2-lactylate",
  "canthaxanthin",
  "caprocaprylobehenin",
  "carmine",
  "CBD/cannabidiol",
  "certified colors",
  "charcoal powder",
  "Citrus Red No. 2",
  "cochineal",
  "cyclodextrin",
  "DATEM",
  "diacetyl (synthetic)",
  "dioctyl sodium sulfosuccinate (DSS)",
  "disodium calcium EDTA",
  "disodium dihydrogen EDTA",
  "disodium EDTA",
  "disodium iron EDTA",
  "dodecyl gallate",
  "EDTA",
  "erythrosine",
  "ethoxyquin",
  "ethyl acrylate (synthetic)",
  "ethylene glycol",
  "eugenyl methyl ether (synthetic)",
  "FD&C Blue No. 1",
  "FD&C Blue No. 2",
  "FD&C Colors",
  "FD&C Green No. 3",
  "FD&C Red No. 3",
  "FD&C Red No. 40",
  "FD&C Yellow No. 5",
  "FD&C Yellow No. 6",
  "foie gras",
  "gamma aminobutyric acid",
  "Garcinia cambogia",
  "gardenia blue",
  "Ginkgo biloba",
  "gold/gold leaf",
  "Grapefruit seed extract",
  "Hawaiian black salt",
  "He shou wu",
  "heptylparaben",
  "hexa-, hepta- and octa-esters of sucrose",
  "high-fructose corn syrup/HFCS",
  "highly branched cyclic dextrin",
  "hijiki",
  "hydrogenated oils",
  "inosine monophosphate",
  "insect Flour",
  "iron oxide",
  "kava/kava kava",
  "lactic acid esters of monoglycerides",
  "lactylated esters of mono- and diglycerides",
  "ma huang",
  "magnesium lactate",
  "mechanically separated meat",
  "melatonin",
  "methyl silicon",
  "methylparaben",
  "microparticularized whey protein derived fat substitute",
  "monoammonium glutamate",
  "monopotassium glutamate",
  "monosodium glutamate",
  "mucuna pruriens",
  "myrcene (synthetic)",
  "natamycin",
  "Nature identical flavors",
  "neotame",
  "nitrites (synthetic)",
  "octyl gallate",
  "olestra",
  "Orange B",
  "partially hydrogenated oils",
  "polydextrose",
  "polyvinylpolypyrrolidone",
  "polyvinylpyrrolidone",
  "potassium alum",
  "potassium benzoate",
  "potassium bisulfite (okay in wine, mead, cider)",
  "potassium metabisulfite (okay in wine, mead, cider)",
  "potassium nitrate",
  "potassium nitrite",
  "potassium propionate",
  "potassium sorbate",
  "propane-1,2-Diol esters of fatty acids",
  "propionates",
  "propionic acid",
  "propyl gallate",
  "propylene glycol esters of fatty acids",
  "propylene glycol mono- and diesters of fats and fatty acids",
  "propylparaben",
  "pulegone (synthetic)",
  "pyridine (synthetic)",
  "saccharin",
  "saccharin sodium salt",
  "salatrim (short and long chain acyl triglyceride molecule)",
  "shark cartilage",
  "smoke flavor (synthetic)",
  "sodium acid sulfate",
  "sodium alum",
  "sodium aluminum phosphate",
  "sodium aluminum sulfate",
  "sodium benzoate",
  "sodium bisulfite (okay in wine, mead, cider)",
  "sodium cyclamate",
  "sodium diacetate",
  "sodium lauryl sulfate",
  "sodium metabisulfite (okay in wine, mead, cider)",
  "sodium nitrate/nitrite (synthetic)",
  "sodium propionate",
  "sodium saccharin",
  "sodium sorbate",
  "sodium stearoyl lactylate",
  "sodium stearoyl-2-lactylate",
  "sodium sulfite (okay in wine, mead, cider)",
  "sorbic acid",
  "soy leghemoglobin",
  "stannous chloride",
  "succistearin",
  "sucralose",
  "sucroglycerides",
  "sucrose acetate isobutyrate",
  "sucrose ester",
  "sucrose polyester",
  "sulfites (okay in wine, mead, cider)",
  "sulfur dioxide (okay in wine, mead, cider)",
  "synthetic caffeine",
  "synthetic ethyl vanillin",
  "synthetic vanillin",
  "TBHQ (tertiary butylhydroquinone)",
  "tetrasodium EDTA",
  "thiodipropionic acid",
  "tonka bean/extract",
  "whale oil"
];